services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_TLS: true
      LDAP_ORGANISATION: "MADAClient"
      LDAP_DOMAIN: "MADA.local"
      LDAP_ADMIN_PASSWORD: "temp"
    ports:
      - "389:389"
      - "636:636"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_ALLOW_INSECURE_ACCESS: "true"
    ports:
      - "8080:80"
    depends_on:
      - openldap
